sed -i "s|REPLACE_WITH_FIREBASE_API_KEY|$FIREBASE_API_KEY|g" config.js
sed -i "s|REPLACE_WITH_FIREBASE_AUTH_DOMAIN|$FIREBASE_AUTH_DOMAIN|g" config.js
sed -i "s|REPLACE_WITH_FIREBASE_PROJECT_ID|$FIREBASE_PROJECT_ID|g" config.js
sed -i "s|REPLACE_WITH_FIREBASE_STORAGE_BUCKET|$FIREBASE_STORAGE_BUCKET|g" config.js
sed -i "s|REPLACE_WITH_FIREBASE_MESSAGING_SENDER_ID|$FIREBASE_MESSAGING_SENDER_ID|g" config.js
sed -i "s|REPLACE_WITH_FIREBASE_APP_ID|$FIREBASE_APP_ID|g" config.js
